package com.example.myenglish.utils

import android.media.AudioManager
import android.media.MediaPlayer
import android.media.ToneGenerator
import android.os.Handler
import android.os.Looper
import android.util.Base64
import java.io.File

object SpokenFeedbackSounds {
    private var lastFeedbackKey = ""
    private var lastFeedbackTimeMs = 0L
    private var wrongSoundFile: File? = null

    fun maybePlay(studentAnswer: String, correctAnswer: String, correct: Boolean) {
        if (!calledFromSpokenHomeworkSpeechResult()) return
        if (studentAnswer.isBlank()) return

        val now = System.currentTimeMillis()
        val feedbackKey = cleanAnswer(studentAnswer) + "|" + cleanAnswer(correctAnswer) + "|" + correct

        if (feedbackKey == lastFeedbackKey && now - lastFeedbackTimeMs < 2500L) return

        lastFeedbackKey = feedbackKey
        lastFeedbackTimeMs = now

        Handler(Looper.getMainLooper()).postDelayed({
            if (correct) playCorrectTone() else playWrongMp3()
        }, 1000L)
    }

    private fun playCorrectTone() {
        try {
            val generator = ToneGenerator(AudioManager.STREAM_MUSIC, 70)
            generator.startTone(ToneGenerator.TONE_PROP_ACK, 140)
            Handler(Looper.getMainLooper()).postDelayed({
                try { generator.release() } catch (_: Exception) { }
            }, 400L)
        } catch (_: Exception) {
            // Feedback sounds should never interrupt the homework flow.
        }
    }

    private fun playWrongMp3() {
        try {
            val file = wrongSoundFile ?: createWrongSoundFile().also { wrongSoundFile = it }
            val player = MediaPlayer()
            player.setDataSource(file.absolutePath)
            player.setOnCompletionListener {
                try { it.release() } catch (_: Exception) { }
            }
            player.prepare()
            player.start()
        } catch (_: Exception) {
            try {
                val generator = ToneGenerator(AudioManager.STREAM_MUSIC, 70)
                generator.startTone(ToneGenerator.TONE_PROP_NACK, 140)
                Handler(Looper.getMainLooper()).postDelayed({
                    try { generator.release() } catch (_: Exception) { }
                }, 400L)
            } catch (_: Exception) {
                // Feedback sounds should never interrupt the homework flow.
            }
        }
    }

    private fun createWrongSoundFile(): File {
        val file = File.createTempFile("myenglish_wrong_feedback", ".mp3")
        file.deleteOnExit()
        file.writeBytes(Base64.decode(WRONG_MP3_BASE64, Base64.DEFAULT))
        return file
    }

    private fun calledFromSpokenHomeworkSpeechResult(): Boolean {
        val stack = Thread.currentThread().stackTrace
        val fromSpokenHomework = stack.any { frame -> frame.className.contains("SpokenHomeworkScreen") }
        val fromSpeechRecognizerResult = stack.any { frame ->
            frame.className.contains("InAppSpeechRecognizer") && frame.methodName == "onResults"
        }
        return fromSpokenHomework && fromSpeechRecognizerResult
    }

    private const val WRONG_MP3_BASE64 =
        "//uUZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWGluZwAAAA8AAAe4AAC9vQAFBQkJCgoODg4SEhYWGhob"
        "Gx8fHyQkJCQkKCgoKC4uLjMzMzM3Nzc3PT09PT09QkJGRkZGR0dMTExMTExTU1NTV1dXV1hbW1tbW2FhYWFhZmZmZmZm"
        "ampqampubm5ubnJycnJ2dnZ2goKCgoaWlpaWlqamtrbCwsLC0tLS0tLi4uLi4yMjIyNDQ0NDg4ODg8PDw8P//////////"
        "AAAAAExhdmY2MC4xNi4xMDAAAAAAAAAAAAAAACQAAAAAAAAHvMmYtsMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//sUZLg"
        "AAGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABGDg7wIlhx+VToG5OO10Wsa1mTQ2bK/LpSaSyFeUelP51W+euQ5"
        "qoxhWUwXcq5Sv72eS/FRnP6f+G5MXg4wf36Nkz/+v/P3LvrFL+ecOnPlBgQlOYeWNKJ2lSlZxTC7Y6QZ2oPO4EFVKh9A6S"
        "TylaZt3T3GEx3vCiHAOB/4NRRsIQZjaVSin01EQmAxFu9v/5xCKo4cBf/6H6suRCcCFEtCIPA72gAESci0kEKIQAAgioCk"
        "gDTwCcoAoB48sAaQoTQTqrHti+/G7LDd1xvu91z1OM7Fr+jy5WT7/0eVqLxrh0uXf8KlYsPPAXwmgIAuvfF2ObDbIq3lE"
        "m4q0OhXlfRWRUuMAmDn+9mA//kqNVYMBQLBvSQaC+gwRVjFu7+C8dGl5+4FfqXvu///////8Aa/CAIt4EloG0W5gWg0CaO"
        "wWWWXsBl1QQfXgAOo7NMAF6HvOyKcEKiArIB8j0ciB8RUnOdRMPvP6gMBlCCcH1mgXYYpghEXIAO1QF0jxygAqqqqqqqqqq"
        "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
        "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq//sUZSAAAGkQSgAL0"
        "AAABpAAAACAAADSAAAAEAAAGkAAABpAAABAe+lbuaBFhTo9EIPbMkwO3TwI+keFYqlXq3lvvf/v/fRRtj1fTb/+1uDxObz7"
        "j///He8duGNVHnx+u2x53QZTFq/v9VS//42aHp5SSU//+aE5/w+wf7qV5pxT7lm/qrLEyQTyaYo2xDADkbTLYh+c75KEVXn"
        "S1nWE8C7Te0sB8QVOn8+f+wiiG9xC1oThdgyowCFQgsIuaQouq66K663dZaa5OV5oWwriX3ZIOM0gWDwMDSJco7ZD5Ra8b"
        "uWZwYwCaGyBL8wMj/7Y//VHxQvoCG/nz1l9QfnQHFiD05AIZwzGCaBPRBOIMnK0/iMDYGLBlT08PjFNIVJIOWptAg7WLS8i"
        "bTJAMus5W6cepf+L///8oKHlO5AiiRkgdFGtDIolYMpPhhNnNjbFcoEno/ACZYL/a7lBsDh6PqOj8HzCipjTTtjOMplT1Ha"
        "86moexdQNwv+ZH3AkVVEY0YCyMDQBOkaP/aoVIEgGA2L5cFVTUlJSUlVREBAQQ0MTHRVVV//sUZTgAAGkQSgAL0AAABpAAAAC"
        "AAADSAAAAEAAAGkAAABpAAABBMJtTtsdVS3ji6Sr8VX2X8lzvxeVL8JIBFyu87wqA6VEVJT4LZCKmCxmpn31j2wJ1Guvk"
        "H2rEvLGng/rL/R/N+s+v9KcjxiMezCQlB/6de1M/n0cQEeK1kyb3b6ttNd/G/kz+v7R/4o3Xse18HPJ6wW0ebm4uX0qAAKP"
        "xBzAkG8RfT4g/wOPff5rdGRa5SxdNbmioxxWXq2JS0x2qGR7Vl7g3P2bHTtMAWEuBQUGB79/brrq+3gFz4hv69CD1O7Wv3"
        "//qf/7r1TWyK4MBpxdRhEmYwyS6WBfEB8ob4MDxbF2oUmUKCafnP/V3PzBn0++2T/1N1bQpYDVFau6OC2BIDQE4bv/1Cj3F"
        "UaBgfTrt2TUNyJf/jizAKMMVTv3//ThEoIyDkQqVhCNgOg9Z2kySGQJkOF6uLGUbIz2spuYf////6e/aqqq8/////wv////"
        "/p////6P/r/8eWpnmgAAAAAqqqB//sUZRIAAGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABIqmapqnx9KMTHA3PVfjB"
        "3ltR2S+3PmsGKnMvn4R6mwo2/Ydg/+/l9fc2kY9v//H//1A3Ke92unE3yBs8ahw7jqYeKxWiLpfWdX/8n//Or+u4NVBx5"
        "DztK7OK7kZ+lxp1v1S+j/1SuF8xIvf+TMj3g/kWORlNts/ifDcqd+KRg8/f/JUgQrBA5RMKCtRbIkdMcVuDRgKBg8YdHyJ"
        "+aHWeJwuHEZBI5ptjky5KsyeO47Krvh55DGgwzu9Ei++e7gbRPFBBYA/q2H7TybYEd8+fGJpByxOwjuG1WEJClIhYHJw5f"
        "j5sZ30+CEeVFUYpMPxZJbV1shDCS3UF+pFMLd1BRhrCsBrb7j+ImftyiF6lvgz58f/6XzSqmwMJBRpXn8XqivL9L5UH/l"
        "/4KoV9VaRbbtQ2b7QrrX/YVXdte2i9yc3XuCYy3EJkMmYzZeZCXlHEBIdys/6//sUZUAAAGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABCpKOHzsMn92p5xfO3z1t4/JQvpPIifAYGgsUy5mTvQr/0zc8N+IA6ttH7n7mcHxdV/wAwLmQ6B6sC46zk1E6uBgUs/6qA0h5/Eb0r1UpiFI7rf6bH1yPYGT1bVlWwJgn+hpQYP9jxASbEYf6n8/2sqLjoSQr4yYH6rb4/fQHR6sCYOVq7FF/VfdJ9Jy08aSkQVBHscuSJ76ZX6+v////gX1/0VLpXiPkH62Kf9f/X+q5Yz/daGRUEfmIUa5IrVGuMYW+kYpdHlRdFcmWlaPcXXz7S1n1ptdRJCcVZNjEhb2PPiDTazYH6ajz+gdGI1WEIQ9vA2AsDPoFX/6+SIc9VCttqAwFIaX+K3CEYsCaRqXDnFyYIxGW1j+/6mow//sUZU4AAGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABCTi//5H5Nf/dcNcypp0Venejc0nwDziD1BwmGAN9IB/XXnV0npDOuCVKe6VptM9ztrEgABlEyYOII/SXuu4EPUWMVzxUATeeNKNVTpIT3nqtvOjRrVpC/Gj5fGa+G+v3/jvb7JCEwZBPRQWFR3+SbKJnvMTtFb9CY6X/n0S14I0tSEwDTnZpCFhzBRf6JeT+Co0GZKUMqhDNp0koPpPxWykCPR7owmjNEpEQv8MDf+cfN/ym5/+AkfXbeqQiUCAoSWrWdK33Nv4J0cf/PjwuF39NcvERa7qHOMJj7DtsSQ/Dl+om4/xfSKxMkk2zHMmSr0U9FvL3AIsX9QQ2w9kEsYEkm57pbBC7gweYTPw6IhNzcWrqn5yP/1CsVOz///sUZVgAAGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABBp1o8D7Vh91OBgYJ11Cc0zbLYhsiJuig8yHFuXBUK8P6WDRfkQ74qOy93sPVhNAMqnh5IqNX5eNcZOd+1BlqF9/ZVqUISev2VDVkWbiT/0m3/UuFh/FmTU/4+KB+bvf/1wpdoowYhXTeME//qtmzAQe+u1OJiUgRcXF3VTdJ333zExOdb/mgH83+Pgff3OWTMkE8DSUVFX0Ip9ZgV2ag4IWbHl+IYfNYqrRzP4TUR2m8xrMGAteB66Yj/8b6qDVeg9TX5qicBe2fu2qUBsHTuxk+jQXgBChLoZDAC2Z8sCxewFJO7iUf+z3lajd///+KoFq//+V8aEF29v9f5epGbL0///sUZVwAAGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABHuSA6YCtVAx3Z2QwEk92qj5fnzkIjQC29ZFfCd4M6hW2JCVxQZzBM7smXFZLPe3kyZrQ5fUtD3Jq0LnEKyc0e4ASkVCZdr5ZytLBXzzBoqDOvgfQWVYxv+L+AWs8mR7xWEwpiKZFdxpLKfqiCvhWQ0WAPKiXZ2d/5xjnQwTTFZr+eHi4x/KpmfG4JbhSDXqeY8tnHrgDO/rz1mO9/f+XsWnqzL5pOOQyFJWyhZo/4KxOGuSRABWZBUl5IzrUt18Y70qV2NwVwOCTMI5AWD4y3V+y3rM9tZI1cW/PzI/vQoUHnzRGDZb1xLIApmgBMEgx0+ePPBcjcv+AejyD3qftoF3nfbSvbH+3//sUZVgAAGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABJTVkV/TY/uLDBgo9GHGId9po/BMo9s2iZOdYl7gABAwCdGb4Wnvcxkp87LNwvQbOCAY7A1E8E9wvdvWBCmtVQ48AxWzKmSxk66iO3lr1/qT/nT/QP3CNv+tdtrmFjRwwMIbBbcKtxsVboIxiDLmFDqNWzDQ8Tv/6JAdBbyf6XlP2LF5WFp68rFWvAj0n+sbDzcU3bXGYNJnEX/gFMvO4RQrdHoES8g76s7MP9/326MAgu+viP/3u/5vzFoaiCJqzOEbRY5NKIEXmqlzq3Ja7RcvF3Wje7/8qZ3vVm/8fz/WFSmqEFBjOCMDIE0IVBz/+FA1UouoFoa1FUEq2aJ//sUZUQAAGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABGKsgrDR8FI3UPArFRCnCw3zN0o1hUs1+8heE5a8JUNw7Xc7sZNWVE6pIIH4c/3moK4e/wU9I1RVPj/Q8WtvMmv6DNgwZgCicFCkN3YdGcf/4MxyCE7P/0jrD///x+ixSa6NdNd6PwruF1k9XBC2LTF70LJAfHRBQ9DMwD4BWBD93/WBzSf+E1oIFoP9O6QqT7fDC1HlFLIocuh2iEnYjVvjbLxLVNVs6nv/AWwMWXBj+WMPFxa//dX/5+tGO/RgGSjBDBY9Yq1p4mfkl8W9TIi76le+a11vohSeFNHu3RrM7vR6Qyd2vBnkEtwzGrPzP/mcRbXKgLwMD5mwGDZqL//sUZUYAAGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABHpVbl38uET5MDsk0yn0PRx9+O3403nQ//1P8kc24rVp5cGV9pNXEZ48DELR0AgYiDCys7/2mBbvW8ohDW9c0v3F3ZH2j94TLtk1xoe+y42DfMwZImCEbTr2JZ1ntsojDkQGGU2Yj/NQEyZfRI5+f+nkJxKkxwprOx4O5Yk5ACklcWy1XX/k3Rj12N5LsrGzPz/+bKDKq00EChgyLEAwoZACT/6KVB+QKowM5xJKAn+4l+wiCRQoX1czwCEss0ISkK57n3Q7iF///+jMwsqJKahQX5TH/n/gRW1aC+jwJU1qbW2KtgNrbI4uSVpfDVUUHye5ci3h2a4wYUrP///sUZVQAAGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABL9D4sQCvBPp+KzfZW9JUzwbNZbGZx2sG8W1NSk2r5c5g0/+xkwxSHbiWqNr1lNYugmBjcp57PmTbrtB9xhPs+UP9WuEkAPCj/rsdzRBmE3AMN4j/+/y9Px7//+/l+v2ytw+X//+f1RZZVBnJSMn0bjGy1f8v5+VdUZV/t/9/8f/IrwvCLJgfqqBeFggmfUFapqepMOZBhnjT/+QUFW+Yxwt/4uCV3Rhr5q0oLzQaG06NCNDAQMB/hVBryvh86CrlQXsh0HafiwIj15nlgoEUTxzJAieRdWEbeXHcVPRGYrjuM4jR8FtX4fH1XwUVGdsNNsdhqORYESLwgszMAwBhoL//sUZUIAAGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABJcHMkxMHwyoCglRQFfAxtIRjQo3qP6zZJfZo1g2WXg7gXYIICwwIFgA+DMyWGikHuUJfnO+rCDkj4xR4Xojff+e/9xzDhxv9ej2tns2+TzkJYXzB3np5s0AAXT5eyLmV3ukwxl37kr1t+3pvEfT7Kz8//lhm0Nw9wT5pX0rExnAQGjR6ma9wueJMn78FcPRFa52N8oVLnGZQ4UCaWyMw+4P/Nlj/7Ipj7w9rrveDEuf/41FN9/MI8xz+vV+w99bH+u5fSIdy0v8l05X+x3Ct6ip2zIiIVa86bQwjDz/B/1o6KRFVTp5dAXne3DMf2DypQURVcDcwZf//sUZVcAAGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABI8FlQ/qFv6+xQfCEGs/371giDDbn5izYOJJ56+IIFH6PJnsLjeUUqg6SfkQs6CCgYuP/DDvwSx+P//rjEyp/3ZU5l5d0fH/bP2Zwcn3KLDhKiyAuH+hmkpT+Iv2L3/MvuLbfwzbeZe+7tEb3ZYVb/6pd1r/4AH9+uqPWPyETiRZhSAocIcoo6ALeuf/iyZBkhT+ST4GOHT23OMI8//GRHcNBp2/k4OHh+CnoJSe8LcW1RXZEy0rmtEf+pc+D9P/qiVpTnLypUKxdWAQKgYEYhxtz/qRIr6KYDGITGOJpd0MHtkRkKKPW3+/+//+dAClQGAKETUp8ycIb3///sUZU4AAGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABFNDhbyH3D7/WGqlK03hHnK05C+OeP98Ifh8Ljx05bp4I4zwmCoA/+KYvMZp4pVKSjODzWDEfk7kbKgz/PAnVS4QAfj/2hNNI29wxf/+aZBozK3C8UVj/rbJkgLlQVRvpE2ZjRSk/0FT6xUf/9dIZ6qCQ+BwsKi+wmJE0H/+HiGnyo6WIYaj0WkyMT5IOHwLriIrVCg1HJRK4dIOxMj+sIz/Jf3///5jKJZTEFOMJ7wdi4GGiaC7ctKow8XlvcABCMtMpSBuFLX/uMdFhkR0lT+DAYCEikS6uZoSpgxkDBkEN8tcXsK//8t+v/CndKPIuE//sUZUwAAGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABL2La45JXfq/m9ZNVoWFw58qxaB02ko6H+Lf68IVpdu3/v3+JrdE8HuHaL/LF8hQ0dTPyORO+GC/Fowbdz/lfD5GBIkM/jdNHThI7GkSpT/m1+svv+/v/ypf+xmg0rEG/L6/OxbUA0yXhn4LoaDk5OT+Jn+wxhIAZUHBlMYYJfU/0O4hnRwr/+xSxkX3sSvwX+PQVeSv8YVCufyqLMe+7SleJ/Wlj9/3JcZ3ssD9ObHJy45YLAUF/3GoE7woVImEXaDX//O1wlDN/8cr/qL/raQuWqWxgxSCoXuDyY/6mwFvUHlHg2+ESXonTTOH3kzZth1+OIIY//sUZVIAAGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABMKxYTU5gJ6uZMsVWa63Si+rknEymxgTMM5sQPfwYwMD/+VxMNhQHsr/6vcqXqLtHtyr1+M1qAsrQI7h1rR/QsqqpocVOMLPxMQvGVCs2P/KH/rHpGcUsOpMB1M8rZkKo/nH/zW+ej9/66l6YpBb/xhR/Kpt3ifGP/zZUn+1c6qkgKDmHDwkgOWA1VjNY99t0EPNxQSkY+//OH/4eTClWC53WCCB0VSQwJrJRgpljH8R4t8/2n///io3yCTtELivdZJfSzMK8hNo6NoPu1gIKWwsTtItXBALL16o08lRhWuI0sLp/UWItM/ep6xVHBs3//sUZUwAAGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABJySBBluQmjTIh/+cKAgG1AYC/C/2n/z//+xguUWtxWqvmiPqX9Y4w5p7HFVORYyBRMRV7+dCh/7WcbnNgmyMsKcuVaVjx9K6a5r/FcBJ9r8//+OqAX/cvQVKYKB++4GqjZ9KP8XWqlxCswiCwxFtA8xDMdM7m6MD5p7E4LHE65b/0Hr6FYfAUEDWovAzofkPX82U5B+xXx7v+CzWDs8X5Py0qcwWRtmSaOW6qiWE4oYaIqEqSyDVukgJZ/Gx//VT5jCipwtwQQEKFDhgQfvPzysGIbXFiu9L/2kgj3q7k8f/v4+pkJvEzD05PAbpNF6sA9vSrMTtb7a+V/Gd8DDwlE9lsb//sUZVcAAGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABHeIjlDymbm77VMocxtDE02ixwF9SB/wglOhFwf3MVB1PsoFmfBCyfxp0JkUwLBisGwM7rVZiPKbKtL8J4he/7nAdvgp5n1aTCA4G90pLtyfeejp3ObmZ2YE6enS01NTU1Yiyl6vYXx/eSf/8q7a9h3+/9Xx2XxTFQbFHMVGC42mlk17Fmn4Ig/02KLtJHHtfu9////+Hj41////n/9DYbEMSG8IaodmJ9p///7+ZyEGgm0dNzNNy1rgaIiUVFbiYxgOCrjr//qiuCV63//+b+37rXi4DHx8pIR92jTUzbyDkaf/J8hKNDFFKb//sUZVwAAGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABJ4VUW/kFCr+6cUj66gaDYwYJjIf+8tGgwW0/1i3fhQGvz6MmuQKEjQyIo/t5IGhSZgVK1T+++XF2kw7X4iS9nrShQhSzqy0Gh+O/6qqZzaB+r3xuMKnHIvEUSI6zbsfKAj+ivxq7VVwCH5m7hx64/i+v4o3kGHv5lhhUED0I//6mT1+/Pz5Ob1Lz6XRPaP/CH/q5aMYcBu4jB/0T/QU/q39Uy2f9RrUFaMjHCDYLQIQ9jP/9l5sf/7frWaCk0oPT//l/f8CTU4Z48CtGTDxGcVH2r3q1VCq2NZ+5CWawgzILo27v//sUZU4AAGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABJ60WqxW4QU//9xM4xoSmfmQQ44FqZf//g5OLz1XK1v5cfEOJCf1dh3d2Q0MwH+YCL/ysYciQuE5htQxP0EUmvq8n//pb10q0YB14r47zy4xovB3Aq/3be6/v///mk84uE+ieVL8cgQuI0vwHVkF7t2hZJcKWWPK/XFJv//XxYGVNYCVa7+d+1X+/wBi13K8lhxA42ubU3P/13xBT10yVgMRf+dBi5jw8J2ZnwEPQho//aMWl8OWw2f//////////////////3p//+j//2EAGf1ihVj2+aj//nbCQAAAAA3/7FGTuH/F//sUZUYAAGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABJ5mxSiCAG8dxi8cXk0OeLm0XrAvWn4Nz3AS+Up39RV4s5i4ztpNlVE03gFZ+R0p0t2xC/5eqptOvaX76V/H7psu/B//f1MHRUe8dJvjJxnBhFaW/1sVohxDP+qEACD1+HEroWOGodP/rdkJolTFWgByv/JOzf8gI8R9/wb3/+Oo/j6dLIuE1Mmn5+H9MPbW4eu/HaxJQnG74I59MiESwSHF/+rY7fRViFdWOeG6oKwk1KgzyqVyoSD//nr/zxg7qXpF/////6r///4fpaRrre/xv///0r5Io1sYezhGgwFAgufZf6A/p2f/2ixFGq2MTX/6qqq//sUZS4AAGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABEeDGuwxziWO/PAxMAqP6NCLo//9f8WDF9WXLspwkZMkicHzmkFLEB/yoZpJ4I2yZOH+HzXiQozEpPv7EDvWyKSQTlcNu/7O1f/0fFsZqRg5sCj1//c/l6jd4knT5FXSLo4Ga5TeT4V59YGB/n67lPDxAI3dAIEIhZWH9MsI4kKC0W/8QqCYBeP1LB9ghv6i86qd7P/3NxiNq5fy/7DwOSGHJj4q7cbpwcpPehAzwlDbH2lFio/2BP/949YDoyuc+FPP+cmAbdzj/7eSf7iYgC2AeHJyYgwkAef/8qf/30fxDIl0UxM4Odn//sUZSkAAGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABF+GBtQxE0WtmVgH3lJToBd7HE/iFKpDGDyMXgr97lA8h+Q+QEVluy4kJ4lgOiVf0LKNNRjgyC2BqIXmGj/I6ZRyumEPbgKfegvB/F81+25/7qC2CbwQW3pCiR/i3uxfJT9R35lbHsI2V7p4GB2X9/iDJIGGQyzAbBGJl/6wNyEcjBoUa3o2/WP/0lwZyrc9ra7On6gbqra9/lRdbab/zK/40qgxLlEySNQZmbrRoaF5/k+jOWDC0A5/6j/zCCh6mlTwXAJDgcwEwP2+P/eQigOD/4MYenatJ00VReU5t2RQiIqCMwZgmX+f//sUZU4AAGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABHhTplRxoRIWIdEoo9cZYZA/UKVf/Yl2Q5+eZGB4f+CW2jp49vXvT/9CqEv/eyJh08ZGM5g2rs7vYW8QSlNNWRxlMXnfz/1783L2JgdGBqzMwUFBf//qapVSGQ/wK+o1q6ERa//rd8xkwvjrB4pH/sYjBgRGAQAAxzjy7OD+cgHlHBNXk2tQEELl/0+GZgEwvT///H+rbOoiBSIJBo0Mw2B4pAHz11MfgKb4D14IHfIg//W/+yhQmBSSwNRy4MhR5GI+Rjhyb5MJ4l8gcHnW5W/2qqoUqVOhvT4zYGB////sUZUoAAGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABEorS6CslEIIQYEAlAyn+vYCh4YwMow1s+J/m36IqIDkhFoGNFQwVYuL/LkDG1lAegpYgIPp//UA2OEp6qeNYs3ycof/0hUbn8/sxY8P+2RFf6D9d6H9Uarf8ZcVFD+AB2dnZxirjJzU1pIZk+JGEqpAwR2lJCi9H//jX///9FIspUegVXoNLr/aEJflQBj/16v9eAgYOZseGxsIxj8WJsJiGGA0NHt1q6Av/R/+JtyENxEDCFB1msEkwMN4skjcf8VsqKZGBj5X/0pxoGUoeVGB4GBq88d6sVGUTpg3Fs1v//66qDjUqKgu8ziP//sUZUIAAGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABGXPoPGMMD2xcLiwn53eYohzZGBiSif///0bbso4PEBggAyh//+dZqYx4FJg51/EKs9D/6L/LNlDMgf+Z/xG/x5fDFwULS589NpN5InXX//8YAjmKCgnjVJxio4mtEUyM9Ke3P/3BuuKxGEMoHJA0Fbn54QH8LI+tqNldKBHeGIQmZGc1g3thLDMA0OBDYU8aG6zGwh7z7+OjvWxhSQaMp1j1IvjuMz5CjG2n+1WoqCQzXjIRbpZKSb8GB9jwrNXJg4GBmUG5H01IBi/Awf6+pXm5v6TdXP6iVkLCyFIjOLDF/Uzpe3+X//sUZUUAGGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABHsHAKXmZkuL4d4HhgbD8EAkEWhWGkoMVZnwEn+APCH9jSyHIA8RjnflWH8T/1WYV1TBxOCu6szkxNjMRgac19VOW6quSTiJdRf7T///syISaMy1Iu8f+QbCAYTGJ/1T1ZYg4GLXf9hErRAE48KCJH/6xYlJTgqiB4OqdlZ3+fwp9hSLhZp+goNRGQBgMyPj//6r6BIaOBhuVCwX0+PmgskQ+FVtMc2yZm09uVGNM9lL+P+Wp/VSDQENfj/JrT/83+CwVIRE4uAYDjr0iyQTweo0SKaoLC//txgQkaQYTCIx/DGi49hP6qsTU//sUZUoAGGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABJU9UCRYWEkQqRIYQdEDCBYlShLgKEIghUIGIPgQ7WAaj5AkGRIWABe4wKhBtvDBmwXNCg/JG3KO/8llgrUYmJFg+5syMefWNuThQ07gP+90QJtExZnx4/1cmAk0WyAOUD/cFU47lAKaGdhCSi8WAUEtH//zVR7CLClzRwqCjKMhMYzHmxn/BBfZoFIM5P/pKpqb6vpS3UXmFbxqGs3JabHjYlq6vP80vv/AAwcAZhtQqJkHv8gGygbxjDfy6UKoPszD/81P72mLRh2+H/MwQFC9VGBVgVZ9G6J6lWtg9QmFyT6v//sUZUgAGGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABKX6CNVGBoA7/OAeWBoa/JZCklNzpqahPA7UT4+MBZkV+LX1kSWLF+e31f/xzVC5byUR0YIIxLARWqEFU4MD//rS7aMEaZBbmIvAGHq9/nFzgW6SgELBYg/THvv9Oz+f51OrvA4yJwOMDW87K+fCOZg4GBhqqBX/zc///qglRg/JKJGYzRTjRkzp+qqri9x//8r/WPq43RUF52/dg2rhnO88fgq5v/HR7nX70Zk19GI+goZ6s6SVuzfmljRhMOq9yzAz/tXk6V6nlxGHK36bPQ7DwMXfQVTgYKqqqjIKgb///sUZU4AGGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABHKcqCNW5sXFYH7g2EQOn+2xn/1Qt2nA4wRE1EDQhcQxAAzhgciYD6owL/6rCDL6v/BTpSgrc7S7v/q08kheMxnU07/+0/9JXpDQZLg2NmLH/7OGVMXLArhMDAnIE/0f/v5VZZOHEy0T2k4wxkLjB/3F7izqffIN/tcgXBf1iNXxnrbAwBEBAff//ztDgvq3bVKemKBIzDsjIHLriQQQQRY4RJIiC7XgZgBjohzv/hwJNkZp9GUNP3/c6b2yK00piP67VQyU2QfTB2E+MiE2Ix/7aY/+qqoEirRTCeXgzB6//sUZU4AGGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABJhkH4WwjuNVhQnpS8Xcc/uODwoVBAXyQVYQGgYGa2r/GuqCckfgE+g8ctYR+5ihJ+2ysF7p78U9QLsboLNAb/0S4q9RBfq2i0SvWpcWplF5yaqNOpCsrZz/68BqUeN3hxsZQDDOGj//8zeIImpcUmtv9lVZFBcXamkr/3X/6liUe9QaaLvEN2Yt7XGb6nC5+oW8s0mTnRZv1W5TQoBIMszC//1xjE1RUaqAE5pqtVnQvH/AqSMB1FQRfISvRFYXhIBBhYDEwP/Zv2y+HwIDGxglTMoVCcKCxywGPOA55mtr///sUZVYAGGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABCqg6JOFNsRjv2M0OAwMH8LFuEwgwxPxa1NJfEz+NDegDXR8CvmtVQNcWMZgxgQYfS9H/rikODlgN/Qf/1xQ6N///8d3vG0o4cJe8uRrVUGDyitFtTQOQarYyqa7fb0eEgzN4fnPySlI1qD0EItf66w8AAK9hOQwB4ZAwRIoZX//////////zGBlQKBPBwBlvMGA+38t8TLQhbpGE/EwDCApoZgYH+qlmxnsQxMxnBExl+pwRzDhMrLCPZkx/0r46/fBAWfKoKCoUKiZsYGyL/v9ESWZDhT9v//1QK63f//6L/Lv//lACQAqqqq//sUZVQAGGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABL0GZ9o0mkZFscgaYxGgwn/Kr/+19YdcXBUJS77t93UfpIYGAwoeDCMPaAMMDA/cdL0H/1Q6RRuhf7KeFJ/p5F//Sqf97JNxKpeEEq3/zW9a05YkbX5r9Fyrmrmz2n///NDKyBKD+ZkZGB4e/37BYRU00C0F0tF//4VYYZrBMn61j+z/ev/QOEohf/z8hBmSWreUa+fy24jEv1F6+3XiX8DZAU0JvoFh+v8EZWqh+KGD4u/2DTADOpMrCQj/hbvZYo8kHhoYhBt1D/N4bkvs4eN5sJZm3egF40k/7+OLyiTP0gf7yY5MCkFh//sUZVYAGGkQSgAL0AAABpAAAACAAADSAAAAEAAAGkAAABpAAABJI3gufD7g+lrgaxRkCySSNmEvoFI8X/v69DBm/b/0WJcKBh7iAjY+v+dWUTjr7veRq30dIsOQ//NO6KMg/+QsoO3OlVBQGvMwmKYfg2DvrHTxgRZPmYm3VrMKgYv/vVQW8SOe9N//+dVmfn6lVwcnLCBP78Xf8f/7GPqhWwwEmQC5+vV9q3XY1P+pxJyYJy8T/JwqKCoEAgU+XOPZrKFgZjBAJD/cTx7/o1D7dgYGC+5sHP+/9ev///w2gtdcVU+NV2MNVQK8s5wxlwWB80FgMteuxxQAAAAqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
        "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
        "qqqqqqqqqqqq//sUZO4P8WsNQ8sGGRAAAA0gAAABAAAB/gAAACAAADSAAAAEqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
        "qqqqqqqqqqqqqqqqqqqqqqqq"
}
